/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ueberschussrechner;
import java.util.*;

/**
 *
 * @author Lenovo
 */
public class EingabeGUI extends javax.swing.JFrame {

    /**
     * Creates new form EingabeGUI
     */
    public EingabeGUI() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jLabelTitel = new javax.swing.JLabel();
        jLabelBuchungsdatum = new javax.swing.JLabel();
        jLabelBuchungsbetrag = new javax.swing.JLabel();
        buttonEinnahme = new java.awt.Button();
        buttonAusgabe = new java.awt.Button();
        jFormattedTextFieldBuchungsdatum = new javax.swing.JFormattedTextField();
        jLabelTitelBuchung = new javax.swing.JLabel();
        textfeldBetrag = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabelTitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitel.setText("Überschussrechner");

        jLabelBuchungsdatum.setText("Buchungsdatum");

        jLabelBuchungsbetrag.setText("Betrag");

        buttonEinnahme.setLabel("Einnahme");
        buttonEinnahme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEinnahmeActionPerformed(evt);
            }
        });

        buttonAusgabe.setLabel("Ausgabe");
        buttonAusgabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAusgabeActionPerformed(evt);
            }
        });

        jFormattedTextFieldBuchungsdatum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextFieldBuchungsdatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldBuchungsdatumActionPerformed(evt);
            }
        });

        jLabelTitelBuchung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitelBuchung.setText("Buchung");

        textfeldBetrag.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBuchungsdatum)
                                .addGap(61, 61, 61)
                                .addComponent(jLabelBuchungsbetrag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonEinnahme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addComponent(buttonAusgabe, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTitelBuchung)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldBuchungsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(textfeldBetrag, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitelBuchung)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuchungsdatum)
                    .addComponent(jLabelBuchungsbetrag))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldBuchungsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfeldBetrag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEinnahme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAusgabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    ArrayList<Integer> einnahmen = new ArrayList<Integer>();
    ArrayList<Integer> ausgaben = new ArrayList<Integer>();

    public ArrayList<Integer> getEinnahmen() {
        return einnahmen;
    }

    public ArrayList<Integer> getAusgaben() {
        return ausgaben;
    }

    public void setEinnahmen(ArrayList<Integer> einnahmen) {
        this.einnahmen = einnahmen;
    }

    public void setAusgaben(ArrayList<Integer> ausgaben) {
        this.ausgaben = ausgaben;
    }
    
    
    
    private void buttonEinnahmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEinnahmeActionPerformed
        // Button Einnahme addet die Zahl zur ArrayList einnahmen. Ausgabe nur Pos 0 im Array.
        
        String ergEinnahmen = textfeldBetrag.getText();
        int zahlEinnahmen = 0;
        try{
            zahlEinnahmen = Integer.parseInt(ergEinnahmen);
        }catch(NumberFormatException ex){
            //Fehlerbehandlung
        }
        einnahmen.add(zahlEinnahmen);
        textfeldBetrag.setText("");
        System.out.println("Einnahmen Pos 0: " + einnahmen.get(0));
        
        //Schließt das Fenster falls man eine neue Eingabe getätigt hat, aber keine Ahnung ob wir das drinne lassen wollen -> oder ob man mehrere gleicheztig machen soll
        setVisible(false);
        //EingabeGUI.super.dispose(); würde auch gehen
    }//GEN-LAST:event_buttonEinnahmeActionPerformed

    private void buttonAusgabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAusgabeActionPerformed
        // Button Ausgabe addet die Zahl zur ArrayList ausgaben. Ausgabe nur Pos 0 im Array.
        String ergAusgaben = textfeldBetrag.getText();
        int zahlAusgaben = 0;
        try{
            zahlAusgaben  = Integer.parseInt(ergAusgaben);
        }catch(NumberFormatException ex){
            //Fehlerbehandlung
        }
        ausgaben.add(zahlAusgaben);
        textfeldBetrag.setText("");
        System.out.println("Ausgaben Pos 0: " + ausgaben.get(0));
        
        //Schließt das Fenster falls man eine neue Eingabe getätigt hat, aber keine Ahnung ob wir das drinne lassen wollen -> oder ob man mehrere gleicheztig machen soll
        setVisible(false);
        //EingabeGUI.super.dispose(); würde auch gehen
        
    }//GEN-LAST:event_buttonAusgabeActionPerformed

    private void jFormattedTextFieldBuchungsdatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldBuchungsdatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldBuchungsdatumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EingabeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EingabeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EingabeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EingabeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EingabeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonAusgabe;
    private java.awt.Button buttonEinnahme;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFormattedTextField jFormattedTextFieldBuchungsdatum;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabelBuchungsbetrag;
    private javax.swing.JLabel jLabelBuchungsdatum;
    private javax.swing.JLabel jLabelTitel;
    private javax.swing.JLabel jLabelTitelBuchung;
    private javax.swing.JFormattedTextField textfeldBetrag;
    // End of variables declaration//GEN-END:variables
}
