/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ueberschussrechner;

import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author Lenovo
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        obereZeile[0] = new ArrayList();
        obereZeile[1] = new ArrayList();
        obereZeile[2] = new ArrayList();
        obereZeile[3] = new ArrayList();
        obereZeile[4] = new ArrayList();
    }

    //TEST
    ArrayList<Integer> einnahmen = new ArrayList<Integer>();
    ArrayList<Integer> ausgaben = new ArrayList<Integer>();

    ArrayList<ArrayList> buchungsliste = new ArrayList<ArrayList>();

    ArrayList[] obereZeile = new ArrayList[6];

    String text;
    int numero = 0;
    
   
   
    //TEST ENDE
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAnzeigetabelle = new javax.swing.JTable();
        jLabelTitel = new javax.swing.JLabel();
        labelGesammtbetrag = new javax.swing.JLabel();
        jLabelGesamtbetraganzeige = new javax.swing.JLabel();
        textfeldBetrag = new javax.swing.JTextField();
        jFormattedTextFieldBuchungsdatum = new javax.swing.JFormattedTextField();
        buttonEinnahme = new java.awt.Button();
        buttonAusgabe = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonListenAusgabe = new java.awt.Button();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableAnzeigetabelle.setAutoCreateRowSorter(true);
        jTableAnzeigetabelle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr.:", "Buchungsdatum", "Einnahmen", "Ausgaben", "Kommentare"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAnzeigetabelle);
        if (jTableAnzeigetabelle.getColumnModel().getColumnCount() > 0) {
            jTableAnzeigetabelle.getColumnModel().getColumn(1).setResizable(false);
            jTableAnzeigetabelle.getColumnModel().getColumn(2).setResizable(false);
            jTableAnzeigetabelle.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabelTitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitel.setText("Überschussrechner");

        labelGesammtbetrag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelGesammtbetrag.setText("0,00€");

        jLabelGesamtbetraganzeige.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGesamtbetraganzeige.setText("Gesamtbetrag:");

        textfeldBetrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfeldBetragActionPerformed(evt);
            }
        });

        jFormattedTextFieldBuchungsdatum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextFieldBuchungsdatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldBuchungsdatumActionPerformed(evt);
            }
        });

        buttonEinnahme.setLabel("Einnahme");
        buttonEinnahme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEinnahmeActionPerformed(evt);
            }
        });

        buttonAusgabe.setLabel("Ausgabe");
        buttonAusgabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAusgabeActionPerformed(evt);
            }
        });

        jLabel1.setText("Buchungsdatum");

        jLabel2.setText("Betrag");

        buttonListenAusgabe.setLabel("Ausgabe Liste");
        buttonListenAusgabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListenAusgabeActionPerformed(evt);
            }
        });

        button1.setLabel("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGesamtbetraganzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(textfeldBetrag, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonEinnahme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonAusgabe, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelGesammtbetrag, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabelTitel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonListenAusgabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldBuchungsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelTitel)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGesammtbetrag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGesamtbetraganzeige, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldBuchungsdatum)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(buttonListenAusgabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfeldBetrag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonEinnahme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAusgabe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void textfeldBetragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfeldBetragActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_textfeldBetragActionPerformed

    private void jFormattedTextFieldBuchungsdatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldBuchungsdatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldBuchungsdatumActionPerformed

    private void buttonEinnahmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEinnahmeActionPerformed
        // Button Einnahme addet die Zahl zur ArrayList einnahmen. Ausgabe nur Pos 0 im Array.

        String ergEinnahmen = textfeldBetrag.getText();
        int zahlEinnahmen = 0;
        try {
            zahlEinnahmen = Integer.parseInt(ergEinnahmen);
        } catch (NumberFormatException ex) {
            //Fehlerbehandlung
        }
        this.einnahmen.add(zahlEinnahmen);
        obereZeile[2].add(textfeldBetrag.getText());

        textfeldBetrag.setText("");

        System.out.println("Einnahmen Pos 0: " + einnahmen.get(0));

        //Label stuff
        System.out.println("Bis hier no fehler");

        numero = einnahmen.get(0);
        text = String.valueOf(numero);
        labelGesammtbetrag.setText(text + "€");

        //Testweise Ausgabe! Funktioniert, nur nicht bei dem Button!
        // for (int i = 0;i<einnahmen.size();i++){
        //     System.out.println(einnahmen.get(i));
        // }

    }//GEN-LAST:event_buttonEinnahmeActionPerformed

    private void buttonAusgabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAusgabeActionPerformed
        // Button Ausgabe addet die Zahl zur ArrayList ausgaben. Ausgabe nur Pos 0 im Array.
        String ergAusgaben = textfeldBetrag.getText();
        int zahlAusgaben = 0;
        try {
            zahlAusgaben = Integer.parseInt(ergAusgaben);
        } catch (NumberFormatException ex) {
            //Fehlerbehandlung
        }
        ausgaben.add(zahlAusgaben);
        obereZeile[3].add(textfeldBetrag.getText());

        textfeldBetrag.setText("");
        System.out.println("Ausgaben Pos 0: " + ausgaben.get(0));
    }//GEN-LAST:event_buttonAusgabeActionPerformed

    private void buttonListenAusgabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListenAusgabeActionPerformed
        // TODO add your handling code here:
        buchungsliste.add(obereZeile[2]);
        buchungsliste.add(obereZeile[3]);
        for (ListIterator<ArrayList> li = buchungsliste.listIterator(0); li.hasNext();) {
            for (ListIterator li2 = li.next().listIterator(0); li2.hasNext();) {
                System.out.println(li2.next());
            }
        }
        buchungsliste.clear();
    }//GEN-LAST:event_buttonListenAusgabeActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableAnzeigetabelle.getModel();
        model.addRow(einnahmen.get(0));

    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button buttonAusgabe;
    private java.awt.Button buttonEinnahme;
    private java.awt.Button buttonListenAusgabe;
    private javax.swing.JFormattedTextField jFormattedTextFieldBuchungsdatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelGesamtbetraganzeige;
    private javax.swing.JLabel jLabelTitel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAnzeigetabelle;
    private javax.swing.JLabel labelGesammtbetrag;
    private javax.swing.JTextField textfeldBetrag;
    // End of variables declaration//GEN-END:variables
}
